/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package roomify.view;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import roomify.controller.ListingController;
import roomify.model.roomlisting;
/**
 *
 * @author psychmist
 */
public class AppRej extends javax.swing.JPanel {
private DefaultTableModel model;
private ListingController listingController;

    /**
     * Creates new form AppRej
     */
    public AppRej() {
        initComponents();
        jButton2.addActionListener(this::jButton2ActionPerformed);

        model = (DefaultTableModel) jTable1.getModel();
    jTable1.setDefaultEditor(Object.class, null); // optional (read-only table)
    listingController = new ListingController();
    loadPendingListings();
    
    }
    
    

    private void setupTable() {
    model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0);

    // optional: make rows non-editable
    jTable1.setDefaultEditor(Object.class, null);
}

private void loadPendingListings() {
    model.setRowCount(0);

    for (roomlisting rl : listingController.getPendingListings()) {
        // show only pending
        if (rl.status != null && rl.status.equalsIgnoreCase("Pending")) {
            model.addRow(new Object[]{
                rl.listingId,
                rl.location,
                rl.maxOccupants,
                rl.pricePerWeek,
                rl.status
            });
        }
    }
}

private Integer getSelectedListingId() {
    int row = jTable1.getSelectedRow();
    if (row == -1) return null;
    return Integer.valueOf(model.getValueAt(row, 0).toString()); // listingId in col 0
}
public void reload() {
    loadPendingListings();
}

    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Fira Sans SemiBold", 0, 18)); // NOI18N
        jLabel1.setText("Rooms");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "RoomID", "Location", "Occupants", "Price", "Avilability"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setBackground(new java.awt.Color(0, 102, 102));
        jButton1.setFont(new java.awt.Font("Fira Sans Condensed SemiBold", 0, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Approve");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setBackground(new java.awt.Color(0, 102, 102));
        jButton2.setFont(new java.awt.Font("Fira Sans Condensed SemiBold", 0, 16)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 51, 51));
        jButton2.setText("Reject");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setBackground(new java.awt.Color(0, 102, 102));
        jButton3.setFont(new java.awt.Font("Fira Sans SemiBold", 0, 16)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Update");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(371, 371, 371)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(524, 524, 524)
                        .addComponent(jButton1)
                        .addGap(27, 27, 27)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(58, 58, 58)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 Integer listingId = getSelectedListingId();
    if (listingId == null) {
        JOptionPane.showMessageDialog(this, "Select a listing first.");
        return;
    }

    boolean ok = listingController.approveListing(listingId);

    JOptionPane.showMessageDialog(this, ok ? "Approved! Room added to Browse Rooms." : "Approval failed!");

    loadPendingListings(); // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
loadPendingListings();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 int row = jTable1.getSelectedRow();

    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Select a listing first.");
        return;
    }

    int listingId = Integer.parseInt(model.getValueAt(row, 0).toString()); 
    // column 0 = listingId

    boolean ok = listingController.declineListing(listingId);

    JOptionPane.showMessageDialog(this, 
        ok ? "Listing rejected!" : "Rejection failed!");

    loadPendingListings();   // refresh table        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
