/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package roomify.view;
import javax.swing.table.DefaultTableModel;
import roomify.model.DataStore;
import roomify.model.Room;
import roomify.model.Request;


/**
 *
 * @author psychmist
 */
public class BrowseRooms extends javax.swing.JPanel {
    private DefaultTableModel model;
private java.util.List<Room> viewRooms = new java.util.ArrayList<>(); // what table is currently showing


    /**
     * Creates new form BrowseRooms
     */
    public BrowseRooms() {
        initComponents();
        model = (DefaultTableModel) jTable1.getModel();
jTable1.setDefaultEditor(Object.class, null);
jTable1.setAutoCreateRowSorter(true);
 refreshRoomsTable();

    }
    
    
   public void refreshRoomsTable() {
    DataStore.seed(); // safe

    viewRooms.clear();
    model.setRowCount(0);

    for (int i = 0; i < DataStore.roomCount; i++) {
        Room r = DataStore.rooms[i];
        if (r != null) {
            viewRooms.add(r);
        }
    }

    // default: show all
    for (Room r : viewRooms) {
        model.addRow(new Object[]{
            r.roomId,
            r.location,
            r.price,
            r.occupants,
            r.availability
        });
    }
}

    private String currentUsername;

public void setCurrentUsername(String username) {
    this.currentUsername = username;
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Fira Sans Compressed SemiBold", 0, 18)); // NOI18N
        jLabel1.setText("Browse Rooms");

        jTextField1.setBackground(new java.awt.Color(102, 102, 102));
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.addActionListener(this::jTextField1ActionPerformed);

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Search");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jTable1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "RoomID", "Location", "Price", "Occupants", "Avilability"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton2.setBackground(new java.awt.Color(0, 102, 102));
        jButton2.setFont(new java.awt.Font("Fira Sans Compressed Book", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Request");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(201, 201, 201)
                                .addComponent(jLabel1)))
                        .addGap(0, 61, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(59, 59, 59)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
int row = jTable1.getSelectedRow();

if (row == -1) {
    javax.swing.JOptionPane.showMessageDialog(this, "Select a room first.");
    return;
}

int roomId = (int) jTable1.getValueAt(row, 0);

// TEMP username (later from session)
String username = currentUsername;

roomify.model.Request r =
    new roomify.model.Request(
        roomify.model.DataStore.nextRequestId++,
        username,
        roomId,
        "Pending"
    );

roomify.model.DataStore.requests.add(r);

javax.swing.JOptionPane.showMessageDialog(this, "Request submitted!");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String keyword = jTextField1.getText().trim().toLowerCase();

    model.setRowCount(0);

    for (int i = 0; i < DataStore.roomCount; i++) {
        Room r = DataStore.rooms[i];
        if (r == null) continue;

        boolean match =
                String.valueOf(r.roomId).contains(keyword) ||
                r.location.toLowerCase().contains(keyword) ||
                r.availability.toLowerCase().contains(keyword) ||
                String.valueOf(r.price).contains(keyword) ||
                String.valueOf(r.occupants).contains(keyword);

        if (keyword.isEmpty() || match) {
            model.addRow(new Object[]{
                r.roomId,
                r.location,
                r.price,
                r.occupants,
                r.availability
            });
        }
    }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
