package roomify.view;
import javax.swing.JOptionPane;
import roomify.controller.AuthController;
import roomify.model.user;
import roomify.view.AdminAcc;
/**
 *
 * @author psychmist
 */
public class LoginFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginFrame.class.getName());

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Left = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        companyname = new javax.swing.JLabel();
        copyright = new javax.swing.JLabel();
        Right = new javax.swing.JPanel();
        Login = new javax.swing.JLabel();
        Username = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        Password = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        lgnbtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        sgntbn = new javax.swing.JButton();
        rollabel = new javax.swing.JLabel();
        role = new javax.swing.JComboBox<>();
        frgtpss = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOGIN");
        setPreferredSize(new java.awt.Dimension(800, 500));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(null);

        Left.setBackground(new java.awt.Color(0, 102, 102));
        Left.setPreferredSize(new java.awt.Dimension(400, 500));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/roomify/view/assets/logo.png"))); // NOI18N

        companyname.setFont(new java.awt.Font("Fira Sans Compressed Medium", 1, 36)); // NOI18N
        companyname.setForeground(new java.awt.Color(255, 255, 255));
        companyname.setText("Roomify");

        copyright.setFont(new java.awt.Font("Fira Sans Condensed Eight", 0, 18)); // NOI18N
        copyright.setForeground(new java.awt.Color(255, 255, 255));
        copyright.setText("All Rights Reserved\n");

        javax.swing.GroupLayout LeftLayout = new javax.swing.GroupLayout(Left);
        Left.setLayout(LeftLayout);
        LeftLayout.setHorizontalGroup(
            LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftLayout.createSequentialGroup()
                .addGroup(LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(copyright, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(LeftLayout.createSequentialGroup()
                            .addGap(117, 117, 117)
                            .addComponent(logo))
                        .addGroup(LeftLayout.createSequentialGroup()
                            .addGap(141, 141, 141)
                            .addComponent(companyname))))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        LeftLayout.setVerticalGroup(
            LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(companyname)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                .addComponent(copyright)
                .addGap(35, 35, 35))
        );

        jPanel1.add(Left);
        Left.setBounds(0, 0, 420, 500);

        Right.setBackground(new java.awt.Color(255, 255, 255));
        Right.setMinimumSize(new java.awt.Dimension(400, 500));

        Login.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        Login.setForeground(new java.awt.Color(0, 102, 102));
        Login.setText("LOGIN");

        Username.setBackground(new java.awt.Color(102, 102, 102));
        Username.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        Username.setText("Username");

        jTextField1.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(102, 102, 102));

        Password.setBackground(new java.awt.Color(102, 102, 102));
        Password.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        Password.setText("Password");

        jPasswordField1.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(102, 102, 102));

        lgnbtn.setBackground(new java.awt.Color(0, 102, 102));
        lgnbtn.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lgnbtn.setForeground(new java.awt.Color(255, 255, 255));
        lgnbtn.setText("Login");
        lgnbtn.addActionListener(this::lgnbtnActionPerformed);

        jLabel4.setText("Don't have an account yet ?");

        sgntbn.setForeground(new java.awt.Color(255, 51, 51));
        sgntbn.setText("Sign Up");
        sgntbn.addActionListener(this::sgntbnActionPerformed);

        rollabel.setBackground(new java.awt.Color(0, 102, 102));
        rollabel.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        rollabel.setText("What's your role ?");

        role.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        role.setForeground(new java.awt.Color(255, 51, 51));
        role.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Member" }));

        frgtpss.setBackground(new java.awt.Color(0, 102, 102));
        frgtpss.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        frgtpss.setForeground(new java.awt.Color(255, 255, 255));
        frgtpss.setText("Forgot Password");
        frgtpss.addActionListener(this::frgtpssActionPerformed);

        javax.swing.GroupLayout RightLayout = new javax.swing.GroupLayout(Right);
        Right.setLayout(RightLayout);
        RightLayout.setHorizontalGroup(
            RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RightLayout.createSequentialGroup()
                .addGroup(RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(RightLayout.createSequentialGroup()
                            .addGap(127, 127, 127)
                            .addComponent(Login))
                        .addGroup(RightLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(lgnbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(frgtpss))
                        .addGroup(RightLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(rollabel))
                            .addGroup(RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(RightLayout.createSequentialGroup()
                                    .addGap(41, 41, 41)
                                    .addComponent(role, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RightLayout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(sgntbn)))))
                    .addGroup(RightLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Username)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Password)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        RightLayout.setVerticalGroup(
            RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RightLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(Login)
                .addGap(58, 58, 58)
                .addComponent(Username)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Password)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rollabel)
                    .addComponent(role, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lgnbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(frgtpss, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(sgntbn, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jPanel1.add(Right);
        Right.setBounds(440, 0, 360, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 119, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 129, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void frgtpssActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frgtpssActionPerformed
      JOptionPane.showMessageDialog(this,
        "Password reset is not implemented in this version.\nPlease contact Admin.");
  // TODO add your handling code here:
    }//GEN-LAST:event_frgtpssActionPerformed

    private void lgnbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lgnbtnActionPerformed
 String username = jTextField1.getText().trim();
    String password = new String(jPasswordField1.getPassword()).trim();
    String selectedRole = role.getSelectedItem().toString().trim(); // "Admin" or "Member"

    if (username.isEmpty() || password.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter username and password.");
        return;
    }

    AuthController auth = new AuthController();
    user loggedIn = auth.login(username, password, selectedRole);

    if (loggedIn == null) {
        JOptionPane.showMessageDialog(this, "Invalid credentials. Try again.");
        return;
    }

    // Open dashboard based on role
    if (loggedIn.getRole().equalsIgnoreCase("Admin")) {
        AdminDashboard ad = new AdminDashboard();

ad.setVisible(true);

    } else {
        UserDashboard ud = new UserDashboard();
ud.setCurrentUsername(loggedIn.getUsername());
ud.setVisible(true);

    }

    this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_lgnbtnActionPerformed

    private void sgntbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sgntbnActionPerformed
RegisterFrame rf = new RegisterFrame();
    rf.setVisible(true);
    this.dispose();       // TODO add your handling code here:
    }//GEN-LAST:event_sgntbnActionPerformed

    /**
     * @param args the command line arguments
     */
    
public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
}
               

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Left;
    private javax.swing.JLabel Login;
    private javax.swing.JLabel Password;
    private javax.swing.JPanel Right;
    private javax.swing.JLabel Username;
    private javax.swing.JLabel companyname;
    private javax.swing.JLabel copyright;
    private javax.swing.JButton frgtpss;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton lgnbtn;
    private javax.swing.JLabel logo;
    private javax.swing.JComboBox<String> role;
    private javax.swing.JLabel rollabel;
    private javax.swing.JButton sgntbn;
    // End of variables declaration//GEN-END:variables

}