/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package roomify.view;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author psychmist
 */
public class MyRequest extends javax.swing.JPanel {

    /**
     * Creates new form MyRequest
     */
    public MyRequest() {
        initComponents();
    }
    public void loadRequestsForUser(String username) {
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0);

    for (roomify.model.Request req : roomify.model.DataStore.requests) {
        if (!req.username.equalsIgnoreCase(username)) continue;

        roomify.model.Room room =
                roomify.model.DataStore.findRoomById(req.roomId);

        if (room == null) {
            model.addRow(new Object[]{
                req.roomId, "Unknown", "-", "-", req.status
            });
        } else {
            double displayPrice =
        (req.proposedPrice != null) ? req.proposedPrice : room.price;

model.addRow(new Object[]{
    room.roomId,
    room.location,
    displayPrice,
    room.occupants,
    room.availability
});
        }
    }
}
    private String currentUsername;

public void setCurrentUsername(String username) {
    this.currentUsername = username;
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Fira Sans Compressed SemiBold", 0, 18)); // NOI18N
        jLabel1.setText("My Request");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "RoomID", "Location", "Price", "Occupants", "Avilability"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setBackground(new java.awt.Color(0, 102, 102));
        jButton1.setFont(new java.awt.Font("Fira Sans Compressed SemiBold", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Delete ");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setBackground(new java.awt.Color(0, 102, 102));
        jButton2.setFont(new java.awt.Font("Fira Sans Compressed SemiBold", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Update");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(419, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(73, 73, 73))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(395, 395, 395))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(39, 39, 39))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
int row = jTable1.getSelectedRow();
    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Select a request first.");
        return;
    }

    int requestId = Integer.parseInt(jTable1.getValueAt(row, 0).toString());

    // remove from DataStore
    roomify.model.DataStore.requests.removeIf(r -> r.id == requestId);

    JOptionPane.showMessageDialog(this, "Request deleted.");
    loadRequestsForUser("member");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
  int row = jTable1.getSelectedRow();
    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Select a request first.");
        return;
    }

    // Column 0 is RoomID (NOT RequestID)
    int roomId = Integer.parseInt(jTable1.getValueAt(row, 0).toString());

    // Demo user
    String username = "member";

    // Find the request by (username + roomId)
    roomify.model.Request target = null;
    for (roomify.model.Request r : roomify.model.DataStore.requests) {
        if (r.roomId == roomId && r.username.equalsIgnoreCase(username)) {
            target = r;
            break;
        }
    }

    if (target == null) {
        JOptionPane.showMessageDialog(this, "Request not found.");
        return;
    }

    String input = JOptionPane.showInputDialog(this, "Enter your new proposed price:");
    if (input == null) return;

    input = input.trim();
    if (input.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Price cannot be empty.");
        return;
    }

    double newPrice;
    try {
        newPrice = Double.parseDouble(input);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Please enter a valid number.");
        return;
    }

    if (newPrice <= 0) {
        JOptionPane.showMessageDialog(this, "Price must be greater than 0.");
        return;
    }

    target.proposedPrice = newPrice;
    target.status = "NegotiationSent";

    JOptionPane.showMessageDialog(this, "Updated! Proposed price sent.");

    loadRequestsForUser(username);// refresh your table method       // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
